# Live Session 4 (30/08/2022) - NumPy
#### By Ika Nurfitriani (PYTN-KS10-008)
Di pertemuan ini akan membahas salah satu library dari Python yaitu Numpy. Terdapat beberapa hal yang akan dipelajari yaitu perbedaan python list dengan numpy array, membuat array lalu cara add, remove, short, shape dan reshape, konversi matriks 1D ke 2D, membuat array baru dengan indexing dan slicing serta operasi dasar pada array.

# Operasi Penjumlahan Vektor
**Menggunakan List**

In [1]:
a = [2, 8, 1, 6]
b = [12, 28, 10, 2]

def jumlah(a, b):
    c = [0] * len(a)
    for i in range(len(a)):
        c[i] = a[i] + b[i]
    return c

**Tipe data dari numpy -> np.array**

In [2]:
import numpy as np

a = [2, 8, 1, 6]
b = [28, 10, 2, 1]
np_a = np.array(a)
np_b = np.array(b)

**Pertambahan list a dengan list b**

In [3]:
a + b

[2, 8, 1, 6, 28, 10, 2, 1]

**Pertambahan list a dengan list b**

In [4]:
np_a + np_b

array([30, 18,  3,  7])

**CEK PERFORMA**

In [5]:
a = [1] * 1000
b = [2] * 1000

**Menghitung lama code ketika dijalankan**

In [6]:
%timeit jumlah(a,b)

213 µs ± 12.3 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


**Menyimpan list a dan b ke dalam numpy array np_a dan np_b**

In [7]:
np_a = np.array(a)
np_b = np.array(b)

**Menghitung lama code ketika dijalankan**

In [8]:
%timeit np_a + np_b

3.22 µs ± 361 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


**Contoh array 1 Dimensi**

In [9]:
a1d = [8,6,4,2,1]
a1d = np.array(a1d)
a1d

array([8, 6, 4, 2, 1])

**Contoh array 2 Dimensi**

In [10]:
a2d = [[6,2],[12,1],[28,6]]
a2d = np.array(a2d)
a2d

array([[ 6,  2],
       [12,  1],
       [28,  6]])

**Jumlah elemen harus sama, berikut contoh jika tidak sama**

In [11]:
a2d = [[1,3],[5,4,5],[7,8]]
a2d = np.array(a2d)
a2d

C:\Users\Ika N\AppData\Local\Temp\ipykernel_2276\3317907818.py:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  a2d = np.array(a2d)


array([list([1, 3]), list([5, 4, 5]), list([7, 8])], dtype=object)

**Membuat list a**

In [12]:
a = [5,7,4,6,2.8,'a']
a

[5, 7, 4, 6, 2.8, 'a']

**Menyimpan list a menjadi numpy array a**

In [13]:
a = np.array(a)
a

array(['5', '7', '4', '6', '2.8', 'a'], dtype='<U32')

**Membuat list A**

In [14]:
A = [[2,6],[8,4],[5,3]]

**Menyimpan list A menjadi numpy array A**

In [15]:
A = np.array(A)
A

array([[2, 6],
       [8, 4],
       [5, 3]])

**Mengakses elemen array baris index ke-2 dan kolom index ke-1**

In [16]:
A[2][1]

3

**Cara lain untuk mengakses elemen array baris index ke-2 dan kolom index ke-1**

In [17]:
A[2,1]

3

**Memanggil baris**

In [18]:
A[1]

array([8, 4])

**Cara lain memanggil baris**

In [19]:
A[1, :]

array([8, 4])

**Memanggil kolom**

In [20]:
A[:, 0]

array([2, 8, 5])

### Special Array

**Membuat array dengan anggota nilai 1**

In [21]:
np.ones((8, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

**Membuat array dengan anggota nilai 1**

In [22]:
np.zeros(8)

array([0., 0., 0., 0., 0., 0., 0., 0.])

**Membuat array dengan bentuk tertentu dan isi bebas**

In [23]:
np.empty(8)

array([0., 0., 0., 0., 0., 0., 0., 0.])

**Membuat array dari range numerik**

In [24]:
np.arange(2,7, 0.6)

array([2. , 2.6, 3.2, 3.8, 4.4, 5. , 5.6, 6.2, 6.8])

**Membuat array dengan nilai merupakan pembagian rata antara nilai awal dan akhir**

In [25]:
np.linspace(1, 12, 50)

array([ 1.        ,  1.2244898 ,  1.44897959,  1.67346939,  1.89795918,
        2.12244898,  2.34693878,  2.57142857,  2.79591837,  3.02040816,
        3.24489796,  3.46938776,  3.69387755,  3.91836735,  4.14285714,
        4.36734694,  4.59183673,  4.81632653,  5.04081633,  5.26530612,
        5.48979592,  5.71428571,  5.93877551,  6.16326531,  6.3877551 ,
        6.6122449 ,  6.83673469,  7.06122449,  7.28571429,  7.51020408,
        7.73469388,  7.95918367,  8.18367347,  8.40816327,  8.63265306,
        8.85714286,  9.08163265,  9.30612245,  9.53061224,  9.75510204,
        9.97959184, 10.20408163, 10.42857143, 10.65306122, 10.87755102,
       11.10204082, 11.32653061, 11.55102041, 11.7755102 , 12.        ])

### Add, Remove and Sort

**Membuat numpy array arr**

In [26]:
arr = np.array([1, 3, 5, 7, 9])

**Menambahkan elemen ke array**

In [27]:
np.append(arr, [1, 2, 4])

array([1, 3, 5, 7, 9, 1, 2, 4])

**Menghapus elemen di posisi 1**

In [28]:
np.delete(arr, 1)

array([1, 5, 7, 9])

**Membuat numpy array baru**

In [29]:
arr = np.array([8, 2, 6, 4, 9, 3, 5, 1, 7])

**Mengurutkan elemen**

In [30]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

### Shape and Size

**Membuat list A**

In [31]:
A = [[2,8],[6,4],[9,5]]

**Menyimpan list A menjadi numpy array A**

In [32]:
A = np.array(A)
A

array([[2, 8],
       [6, 4],
       [9, 5]])

**Menunjukkan jumlah axes/dimensi dari array**

In [33]:
A.ndim

2

**Menunjukkan bentuk larik**

In [34]:
A.shape

(3, 2)

**Menunjukkan jumlah total elemen array**

In [35]:
A.size

6

### Reshape

**Membuat list a**

In [36]:
a = [6,5,3,8,7,9,4,10]

**Menyimpan list a menjadi numpy array a**

In [37]:
a = np.array(a)
a

array([ 6,  5,  3,  8,  7,  9,  4, 10])

**Memberikan bentuk baru ke array tanpa mengubah datanya**

In [38]:
a.reshape((2,4))

array([[ 6,  5,  3,  8],
       [ 7,  9,  4, 10]])

**Bentuk transpose dari matriks a**

In [39]:
a.reshape((2,4)).T

array([[ 6,  7],
       [ 5,  9],
       [ 3,  4],
       [ 8, 10]])

**Memberikan bentuk baru ke array tanpa mengubah datanya**

In [40]:
a.reshape((4,2))

array([[ 6,  5],
       [ 3,  8],
       [ 7,  9],
       [ 4, 10]])

### Convert 1D to 2D

**Membuat list a**

In [41]:
a = [6,5,3,8,7,9,4,10]

**Menyimpan list a menjadi numpy array a**

In [42]:
a = np.array(a)
a

array([ 6,  5,  3,  8,  7,  9,  4, 10])

**Meningkatkan dimensi array sebesar satu dimensi bila digunakan sekali**

In [43]:
a[np.newaxis]

array([[ 6,  5,  3,  8,  7,  9,  4, 10]])

**Meningkatkan dimensi array sebesar satu dimensi bila digunakan sekali**

In [44]:
a[:,np.newaxis]

array([[ 6],
       [ 5],
       [ 3],
       [ 8],
       [ 7],
       [ 9],
       [ 4],
       [10]])

**Mencetak numpy array a**

In [45]:
a

array([ 6,  5,  3,  8,  7,  9,  4, 10])

**Memperluas array dengan memasukkan axis baru pada posisi yang ditentukan**

In [46]:
np.expand_dims(a, axis=1).shape

(8, 1)

**Menampilkan tuple integer yang menunjukkan jumlah elemen yang disimpan di sepanjang setiap dimensi array**

In [47]:
a.shape

(8,)

### Indexing and Slicing

**Membuat dan mencetak numpy array a**

In [48]:
a = np.array([[14,13,12,11], [10,9,8,7], [6,5,4,3]])
a

array([[14, 13, 12, 11],
       [10,  9,  8,  7],
       [ 6,  5,  4,  3]])

**Menampilkan semua elemen yang memenuhi kondisi tertentu misal yang nilainya lebih sama dengan dari 6**

In [49]:
print(a[a>=6])

[14 13 12 11 10  9  8  7  6]


**Select elements that are divisible by 2**

In [50]:
divisible_by_2 = a[a%2==0]
print(divisible_by_2)

[14 12 10  8  6  4]


**Select elements that satisfy two conditions using the & and | operators**

In [51]:
c = a[(a > 3) & (a < 13)]
print(c)

[12 11 10  9  8  7  6  5  4]


### Creating Array from Existing Data

**Menentukan slice/mengiris array**

In [52]:
arr = np.array([3,4,5,6,7,8,9,10,11,12])
arr1 = arr[5:10]
arr1

array([ 8,  9, 10, 11, 12])

**Menumpuk secara vertikal**

In [53]:
a1 = np.array([[5,5], [6,6]])
a2 = np.array([[7,7], [8,8]])
np.vstack((a1, a2))

array([[5, 5],
       [6, 6],
       [7, 7],
       [8, 8]])

**Menumpuk secara horizontal**

In [54]:
np.hstack((a1, a2))

array([[5, 5, 7, 7],
       [6, 6, 8, 8]])

**Membagi sebuah array menjadi beberapa array yang lebih kecil dengan hsplit**

In [55]:
arrsplit = np.array([[3,4,5,6,7,8,9,10,11,12,13,14], [15,16,17,18,19,20,21,22,23,24,25,26]])
np.hsplit(arrsplit,4)

[array([[ 3,  4,  5],
        [15, 16, 17]]),
 array([[ 6,  7,  8],
        [18, 19, 20]]),
 array([[ 9, 10, 11],
        [21, 22, 23]]),
 array([[12, 13, 14],
        [24, 25, 26]])]

**Membuat objek array baru yang terlihat sama dengan array asli dengan view**

In [56]:
a = np.array([[3,4,5,6], [7,8,9,10], [11,12,13,14]])
b = a.view()
b

array([[ 3,  4,  5,  6],
       [ 7,  8,  9, 10],
       [11, 12, 13, 14]])

**Membuat salinan lengkap dari array dan datanya dengan copy**

In [57]:
c = a.copy()
c

array([[ 3,  4,  5,  6],
       [ 7,  8,  9, 10],
       [11, 12, 13, 14]])

### Basic array operations

**Penjumlahan elemen dalam array 1D**

In [58]:
a = np.array([3,4,5,6])
a.sum()

18

**Penjumlahan elemen dalam array 2D**

In [59]:
b = np.array([[3,4], [5,6]])
b.sum(axis=0)

array([ 8, 10])

**Membuat numpy array baru**

In [60]:
data = np.array([5, 6])
data

array([5, 6])

**Membuat array dengan anggota nilai 1**

In [61]:
ones = np.ones(2)
ones

array([1., 1.])

**Menambahkan array data dengan array ones**

In [62]:
data + ones

array([6., 7.])

**Mengalikan array data dengan array data**

In [63]:
data * data

array([25, 36])

**Membagikan array data dengan array data**

In [64]:
data / data

array([1., 1.])

**Membuat numpy array A dan B**

In [65]:
A = np.array([[3,4], [5,6]])
B = np.array([[7,8], [9,10]])

**Menambahkan array A dengan array B**

In [66]:
A + B

array([[10, 12],
       [14, 16]])

**Mengalikan array A dengan array B**

In [67]:
A * B

array([[21, 32],
       [45, 60]])

**Perkalian matriks secara aljabar linear**

In [68]:
A @ B

array([[ 57,  64],
       [ 89, 100]])

**Mencari rata-rata dari array A**

In [69]:
A.mean(axis=0)

array([4., 5.])

**Membuat array random antara 1 sampai 2**

In [70]:
np.random.random((1,2))

array([[0.90529618, 0.93363955]])

**Membuat array dari range numerik 0 sampai 6**

In [71]:
C = np.arange(0,6)

**Memberikan bentuk baru ke array tanpa mengubah datanya**

In [72]:
C = C.reshape((3,2))
C

array([[0, 1],
       [2, 3],
       [4, 5]])