# Live Session 9
## Descriptive Statistics
#### By Ika Nurfitriani (PYTN-KS10-008)
Di pertemuan ini akan membahas statistik deskriptif. Terdapat beberapa hal yang akan dipelajari yaitu Mean, Weighted mean, Geometric mean, Harmonic mean, Median, Mode untuk kategori Measures of central tendency dan Variance, Standard deviation, Skewness, Percentiles, Ranges untuk kategori Measures of Variability.

### Introduction
***
**Descriptive statistics/Statistik deskriptif** melibatkan summarizing/meringkas dan mengatur data sehingga dapat dengan mudah dipahami.

Terdapat dua kategori dari statistik deskriptif, yaitu Measures of Central Tendency dan Measures of Variability (Spread).

**Population and Samples**, populasi adalah sekumpulan dari semua elemen atau item yang kita minati sedangkan sampel adalah subset dari populasi. 

**Outliers/Pencilan**, adalah titik data yang berbeda secara signifikan dari sebagian besar data yang diambil dari sampel atau populasi. Beberapa kemungkinan penyebab pencilan:

- Variasi alami data
- Perubahan perilaku sistem yang diamati
- Kesalahan dalam pengumpulan data

**Measure of Central Tendency**, mengacu pada gagasan bahwa ada suatu bilangan yang paling baik untuk meringkas seluruh rangkaian pengukuran, sebuah bilangan yang dalam beberapa hal merupakan “central” dari himpunan tersebut.

**Mean/Average**, adalah central tendency dari data, angka diantara seluruh data tersebut atau angka tunggal yang dapat memperkirakan nilai sekumpulan data.

**Median**, adalah nilai yang membagi data dalam 2 bagian yang sama yaitu jumlah suku sisi kanannya sama dengan jumlah suku di sisi kirinya saat data disurun dalam urutan naik atau turun atau arti lainnya ialah nilai "tengah"/titik tengah dalam data kita dan disebut "persentil ke-50".

**Mode**, adalah nilai yang muncul secara maksimum dalam kumpulan data, nilai yang memiliki frekuensi tertinggi.

**Measure of Variability (Spread/Dispersion)**, mengacu pada gagasan variabilitas dalam data. juga digunakan untuk mengukur seberapa 'bagus', mean merepresentasikan kumpulan data.

**Standard Deviation/Simpangan Baku**, adalah pengukuran jarak rata-rata antara setiap besaran dan mean. Standar deviasi yang rendah menunjukkan bahwa titik data cenderung mendekati rata-rata kumpulan data, sedangkan Standar deviasi yang tinggi menunjukkan bahwa titik data tersebar di nilai yang lebih luas.

**Mean Deviation/Mean Absolute Deviation**, adalah rata-rata perbedaan absolut antara setiap nilai dalam satu sel nilai, dan rata-rata semua nilai dari set itu.

**Variance**, adalah kuadrat jarak rata-rata antara setiap kuantitas dan mean atau kuadrat dari standar deviasi. Varians dihitung dengan mencari selisih antara setiap titik data dan mean, mengkuadratkan, menjumlahkan, kemudian mengambil rata-rata dari angka-angka itu.

**Range/Rentang**, adalah perbedaan antara nilai terendah dan tertinggi.

**Percentile/Persentil**, adalah cara untuk merepresentasikan posisi suatu nilai dalam kumpulan data. Untuk menghitungnya, nilai dalam kumpulan data harus selalu dalam urutan ascending/menaik. Berikut terdapat tiga quartiles yang merupakan persentil yang membagi dataset menjadi empat bagian:
- First quartile: Sampel persentil ke-25 atau kuartil pertama yang membagi sekitar 25% item terkecil dari kumpulan data lainnya.
- Second quartile: Sampel persentil ke-50/median atau 25% item terletak di antara kuartil pertama dan kedua dan 25% lainnya antara kuartil kedua dan ketiga.
- Third quartile: Sampel persentil ke-75 atau kuartil ketiga yang membagi sekitar 25% item terbesar dari sisa kumpulan data.

**Quartiles**, adalah nilai yang membagi data menjadi beberapa quarters jika data diurutkan dalam urutan ascending/menaik.

**Skewness**, adalah ukuran asimetri distribusi probabilitas dari real-valued random variabel tentang meannya. Nilai kemiringan bisa positif atau negatif, atau undefined. 
- Distribusi normal: Ekor di kedua sisi kurva sama persis yang tepat satu sama lain.
- Negative skewness/kemiringan negatif: distribusi miring ke kiri, ekor sisi kiri kurva lebih panjang daripada ekor sisi kanan dan mean lebih kecil dari mode.
- Positive skewness/kemiringan positif: distribusi miring ke kanan, ekor sisi kanan kurva lebih panjang daripada ekor sisi kiri dan mean lebih besar dari mode.

**Kurtosis**, adalah ukuran apakah data bersifat hevy-tailed (banyak outlier) atau light-tailed (kurang outlier) relatif terhadap distribusi normal. Ada 3 tipe dari kurtosis:
- Mesokurtic/Mesokurtik: distribusi yang memiliki kurtosis serupa dengan kurtosis bedistribusi normal, yaitu nol.
- Leptokuric/Leptokurtik: distribusi yang memiliki kurtosis lebih besar dari pada distribusi mesokurtik.
- Playkurtic/Playkurtik: distribusi yang memiliki kurtosis lebih rendah dari distribsi mesokurtik.

**Correlation/Korelasi**, adalah teknik statistik yang dapat menunjukkan apakah dan seberapa kuat variabel terkait/related.
- Jika r mendekati 0, artinya tidak ada hubungan antar variabel.
- Jika r positif, berarti semakin besar satu variabel, variabel lainnya semakin besar.
- Jika r negatif, berarti semakin besar satu variabel, variabel yang lain akan semakin kecil (sering disebut korelasi "inversi").

### Practice on Python
***

In [1]:
# Import semua packages yang dibutuhkan
import math
import statistics
import numpy as np
import scipy.stats
import pandas as pd

In [2]:
# Membuat list Python yang berisi beberapa data numerik
x = [7.0, 1, 2.5, 5, 22.0]
x_with_nan = [7.0, 1, 2.5, math.nan, 5, 22.0]
print(x)
print(x_with_nan)

[7.0, 1, 2.5, 5, 22.0]
[7.0, 1, 2.5, nan, 5, 22.0]


In [3]:
# Membuat objek np.ndarray dan pd.Series yang sesuai dengan x dan x_with_nan
y, y_with_nan = np.array(x), np.array(x_with_nan)
z, z_with_nan = pd.Series(x), pd.Series(x_with_nan)
print(y)
print(y_with_nan)
print(z_with_nan)

[ 7.   1.   2.5  5.  22. ]
[ 7.   1.   2.5  nan  5.  22. ]
0     7.0
1     1.0
2     2.5
3     NaN
4     5.0
5    22.0
dtype: float64


### Measures of Central Tendency
#### - Mean

In [4]:
# Tanpa mengimpor pustaka lain (Python pure)
mean_ = sum(x) / len(x)
mean_

7.5

In [5]:
# Menerapkan fungsi statistics built-in Python
mean_ = statistics.mean(x)
print(mean_)

7.5


In [6]:
mean_ = statistics.mean(x_with_nan)
print(mean_)

nan


In [7]:
# Menggunakan NumPy
mean_ = np.mean(y)
mean_

7.5

In [8]:
# Menggunakan method .mean()
mean_ = y.mean()
mean_

7.5

In [9]:
# Menggunakan mean() dan method .mean() dari NumPy
print(np.mean(y_with_nan))
print(y_with_nan.mean())

nan
nan


In [10]:
# Mengabaikan nan dengan menggunakan np.nanmean()
np.nanmean(y_with_nan)

7.5

In [11]:
# Menggunakan method .mean() dari pd.Series objects
mean_ = z.mean()
mean_

7.5

In [12]:
# Menggunakan .mean() dari Pandas yang mengabaikan nilai secara default
z_with_nan.mean()

7.5

#### - Weighted Mean

In [13]:
# Tanpa mengimpor pustaka lain (Python pure)
0.3 * 3 + 0.6 * 5 + 0.3 * 8

6.3

In [14]:
# Menggabungkan sum() dengan range() atau zip()
x = [9.0, 2, 3.5, 5, 29.0]
w = [0.2, 0.3, 0.4, 0.35, 0.25]

wmean = sum(w[i] * x[i] for i in range(len(x))) / sum(w)
print(wmean)

wmean = sum(x_ * w_ for (x_, w_) in zip(x, w)) / sum(w)
print(wmean)

8.533333333333333
8.533333333333333


In [15]:
# Menggunakan np.average() dari array NumPy atau Series Pandas
y, z, w = np.array(x), pd.Series(x), np.array(w)

wmean = np.average(y, weights=w)
print(wmean)

wmean = np.average(z, weights=w)
print(wmean)

8.533333333333333
8.533333333333333


In [16]:
# Menggunakan element-wise produc w * y dengan np.sum() atau .sum()
(w * y).sum() / w.sum()

8.533333333333333

#### - Harmonic Mean

In [17]:
# Tanpa mengimpor pustaka lain (Python pure)
hmean = len(x) / sum(1 / item for item in x)
hmean

4.419662296192365

In [18]:
# Menggunakan statistics.harmonic_mean()
hmean = statistics.harmonic_mean(x)
hmean

4.4196622961923655

In [19]:
# Menggunakan scipy
scipy.stats.hmean(y)

4.419662296192365

In [20]:
scipy.stats.hmean(z)

4.419662296192365

#### - Geometric Mean

In [21]:
# Tanpa menggunakan pustaka lain (Python pure)
gmean = 1

for item in x:
    gmean *= item

gmean **= 1 / len(x)
gmean

6.196432317485006

In [22]:
# Menggunakan scipy.stats.gmean()
scipy.stats.gmean(y)

6.196432317485006

In [23]:
scipy.stats.gmean(z)

6.196432317485006

#### - Median

In [24]:
# Tanpa menggunakan pustaka lain (Python pure)
n = len(x)
if n % 2:
    median_ = sorted(x)[round(0.5*(n-1))]
else:
    x_ord, index = sorted(x), round(0.5 * n)
    median_ = 0.5 * (x_ord[index-1] + x_ord[index])

median_

5

In [25]:
# Melihat kembali variabel x
x

[9.0, 2, 3.5, 5, 29.0]

In [26]:
# Menggunakan median_low() dan median_high()
statistics.median_low(x[:-1])

3.5

In [27]:
statistics.median_high(x[:-1])

5

In [28]:
# Menggunakan median(), median_low() dan median_high() yang tidak mengembalikan nan ketika ada nilai nan diantara titik data
print(statistics.median(x_with_nan))
print(statistics.median_low(x_with_nan))
print(statistics.median_high(x_with_nan))

6.0
5
7.0


In [29]:
# Menggunakan np.median()
median_ = np.median(y)
print(median_)

5.0


In [30]:
median_ = np.median(y[:-1])
print(median_)

4.25


#### - Mode

In [31]:
# Tanpa menggunakan pustaka lain (Python pure)
u = [3, 4, 3, 9, 13]
v = [13, 16, 13, 16, 22, 16, 13]
mode_ = max((u.count(item), item) for item in set(u))[1]
mode_

3

In [32]:
# Menggunakan statistics.model()
mode_ = statistics.mode(u)
mode_

3

In [33]:
# Menggunakan scipy.stats.model()
u, v = np.array(u), np.array(v)
mode_ = scipy.stats.mode(u)
mode_

ModeResult(mode=array([3]), count=array([2]))

In [34]:
mode_ = scipy.stats.mode(v)
mode_

ModeResult(mode=array([13]), count=array([3]))

In [35]:
# Mendapatkan mode & jumlah kemunculannya sebagai array NumPy dengan dot notation
print(mode_.mode)
print(mode_.count)

[13]
[3]


In [36]:
# Menggunakan metode .mode() milik objek Pandas Series
u, v, w = pd.Series(u), pd.Series(v), pd.Series([3, 3, math.nan])
print(u.mode())
print(v.mode())
print(w.mode())

0    3
dtype: int32
0    13
1    16
dtype: int32
0    3.0
dtype: float64


### Measures of Variability (Spread/Dispersion)
#### - Variance

In [37]:
# Tanpa menggunakan pustaka lain (Python pure)
n = len(x)
mean_ = sum(x) / n
var_ = sum((item - mean_)**2 for item in x) / (n - 1)
var_

123.19999999999999

In [38]:
# Menggunakan statistics.variance()
var_ = statistics.variance(x)
var_

123.2

In [39]:
# Menggunakan np.var() atau method .var() milik NumPy
var_ = np.var(y, ddof=1)
var_

123.19999999999999

In [40]:
var_ = y.var(ddof=1)
var_

123.19999999999999

In [41]:
# Metode .var() milik objek pd.Series
z.var(ddof=1)

123.19999999999999

#### - Standard Deviation

In [42]:
# Tanpa menggunakan pustaka lain (Python pure)
std_ = var_ ** 0.5
std_

11.099549540409285

In [43]:
# Menggunakan statistics.stdev()
std_ = statistics.stdev(x)
std_

11.099549540409287

In [44]:
# Mengabaikan nilai nan menggunakan np.nanstd()
np.std(y, ddof=1)

11.099549540409285

In [45]:
y.std(ddof=1)

11.099549540409285

In [46]:
# Menggunakan method .std() milik objek pd.Series
z.std(ddof=1)

11.099549540409285

#### - Skewness

In [47]:
# Tanpa menggunakan pustaka lain (Python pure)
x = [9.0, 2, 3.5, 5, 29.0]
n = len(x)
mean_ = sum(x) / n
var_ = sum((item - mean_)**2 for item in x) / (n-1)
std_ = var_ ** 0.5

skew_ = (sum((item - mean_)**3 for item in x) * n / ((n - 1) * (n - 2) * std_**3))
skew_

1.9470432273905929

In [48]:
# Menghitung sample skewness dengan scipy.stats.skew()
y, y_with_nan = np.array(x), np.array(x_with_nan)
scipy.stats.skew(y, bias=False)

1.9470432273905927

In [49]:
scipy.stats.skew(y_with_nan, bias=False)

nan

In [50]:
# Menggunakan metode .skew() milik objek Pandas Series
z, z_with_nan = pd.Series(x), pd.Series(x_with_nan)
z.skew()

1.9470432273905924

In [51]:
z_with_nan.skew()

1.8339746487317865

#### - Percentiles & Quartiles

In [52]:
# Membuat list data
x = [-6.0, -2.1, 1.1, 3.0, 9.0, 13.8, 22.0, 26.8, 42.0]

# Menggunakan np.percentile() untuk mencari persentil ke-5. ke-95, ke-25, ke-50 dan ke-75
y = np.array(x)
np.percentile(y, 5)

-4.4399999999999995

In [53]:
np.percentile(y, 95)

35.919999999999995

In [54]:
np.percentile(y, [25, 50, 75])

array([ 1.1,  9. , 22. ])

In [55]:
# Menggunakan np.nanpercentile() untuk mengabaikan nilai nan
y_with_nan = np.insert(y, 2, np.nan)
y_with_nan

array([-6. , -2.1,  nan,  1.1,  3. ,  9. , 13.8, 22. , 26.8, 42. ])

In [56]:
np.nanpercentile(y_with_nan, [25, 50, 75])

array([ 1.1,  9. , 22. ])

In [57]:
# Menggunakan statistics.quantiles()
statistics.quantiles(x, n=2)

[9.0]

In [58]:
statistics.quantiles(x, n=4, method='inclusive')

[1.1, 9.0, 22.0]

In [59]:
# Menggunakan np.quantile() dan np.nanquantile() milik NumPy
np.quantile(y, 0.05)

-4.4399999999999995

In [60]:
np.quantile(y, 0.95)

35.919999999999995

In [61]:
np.quantile(y, [0.25, 0.5, 0.75])

array([ 1.1,  9. , 22. ])

In [62]:
np.nanquantile(y_with_nan, [0.25, 0.5, 0.75])

array([ 1.1,  9. , 22. ])

In [63]:
# Menggunakan method .quantile() milik pd.Series
z, z_with_nan = pd.Series(y), pd.Series(y_with_nan)
z.quantile(0.05)

-4.4399999999999995

In [64]:
z.quantile(0.95)

35.919999999999995

In [65]:
z.quantile([0.25, 0.5, 0.75])

0.25     1.1
0.50     9.0
0.75    22.0
dtype: float64

In [66]:
z_with_nan.quantile([0.25, 0.5, 0.75])

0.25     1.1
0.50     9.0
0.75    22.0
dtype: float64

#### - Ranges

In [67]:
# Menggunakan np.ptp()
np.ptp(y)

48.0

In [68]:
np.ptp(z)

48.0

In [69]:
np.ptp(y_with_nan)

nan

In [70]:
np.ptp(z_with_nan)

nan

In [71]:
# Menggunakan numpy
np.amax(y) - np.amin(y)

48.0

In [72]:
np.nanmax(y_with_nan) - np.nanmin(y_with_nan)

48.0

In [73]:
y.max() - y.min()

48.0

In [74]:
z.max() - z.min()

48.0

In [75]:
z_with_nan.max() - z_with_nan.min()

48.0

In [76]:
# Interquartile range
quartiles = np.quantile(y, [0.25, 0.75])
quartiles[1] - quartiles[0]

20.9

In [77]:
quartiles = z.quantile([0.25, 0.75])
quartiles[0.75] - quartiles[0.25]

20.9

### Measures of Correlation Between Pairs of Data

In [78]:
x=list(range(-10,11))
y=[1, 3, 3, 3, 3, 4, 4, 7, 8, 5, 8, 7, 7, 10, 5, 6, 6, 11, 12, 13, 15]
x_, y_ = np.array(x), np.array(y)
x__, y__ = pd.Series(x_), pd.Series(y_)

#### - Covariance

In [79]:
# Tanpa menggunakan pustaka lain (Python pure)
n=len(x)
mean_x, mean_y = sum(x) / n, sum(y) / n
cov_xy = (sum((x[k] - mean_x) * (y[k] - mean_y) for k in range(n)) / (n-1))
cov_xy

19.95

In [80]:
# Menggunakan cov()
cov_matrix = np.cov(x_, y_)
cov_matrix

array([[38.5       , 19.95      ],
       [19.95      , 13.91428571]])

In [81]:
# Menggunakan metode .cov() milik Series Pandas
cov_xy = x__.cov(y__)
cov_xy

19.95

In [82]:
cov_xy = y__.cov(x__)
cov_xy

19.95

#### - Correlation Coefficient

In [83]:
# Tanpa menggunakan pustaka lain (Python pure)
var_x = sum((item -mean_x)**2 for item in x) / (n-1)
var_y = sum((item -mean_y)**2 for item in y) / (n-1)
std_x, std_y = var_x ** 0.5, var_y ** 0.5
r = cov_xy / (std_x * std_y)
r

0.861950005631606

In [84]:
# Menggunakan pearsonr() milik scipy.stats
r, p = scipy.stats.pearsonr(x_, y_)
r

0.8619500056316058

In [85]:
p

5.122760847201207e-07

In [86]:
# Menggunakan np.corrcoef()
corr_matrix = np.corrcoef(x_, y_)
corr_matrix

array([[1.        , 0.86195001],
       [0.86195001, 1.        ]])

In [87]:
scipy.stats.linregress(x_, y_)

LinregressResult(slope=0.5181818181818181, intercept=6.714285714285714, rvalue=0.861950005631606, pvalue=5.122760847201164e-07, stderr=0.06992387660074979, intercept_stderr=0.4234100995002589)

In [88]:
result = scipy.stats.linregress(x_, y_)
r = result.rvalue
r

0.861950005631606

In [89]:
# Menggunakan method .corr() milik Series Pandas
r = x__.corr(y__)
r

0.8619500056316061

In [90]:
r = y__.corr(x__)
r

0.861950005631606